apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zoeru6ir2-go 
  janus-idp.io/tekton: zoeru6ir2-go
  backstage.io/kubernetes-id: zoeru6ir2-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zoeru6ir2-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml