apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zoeru6ir2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:39246bdd1633eb82ea2a40b9d61f3d887a503b81@sha256:c08abac7ec39358d02bca73f667f097ee4f3b2fafe8c2e1937bb4ca3778dc3d6
          name: container-image
